fix: icon size
appworks-lab/toolkit pull request #30
Opened 2021-06-10 06:54 UTC by luhc228

Before:
![image](https://user-images.githubusercontent.com/44047106/121478415-93e27c00-c9fb-11eb-8bf1-84b8679041da.png)

After:
![image](https://user-images.githubusercontent.com/44047106/121478505-aceb2d00-c9fb-11eb-89ec-cf8dd1b7201e.png)

2021-06-10 06:54 UTC, fyangstudio approved these changes

2021-06-12 10:38 UTC, alvinhui commented
看一下文件大小，增加太多了，建议用 compresspng.com 压缩一下。

2021-06-12 10:38 UTC, alvinhui requested changes
看一下文件大小，增加太多了，建议用 compresspng.com 压缩一下。

2021-06-15 02:11 UTC, luhc228 commented
> 看一下文件大小，增加太多了，建议用 compresspng.com 压缩一下。

done

2021-06-15 05:39 UTC, alvinhui approved these changes

2021-06-28 02:35 UTC, merged