Feat: add recommend icon to registry
appworks-lab/toolkit pull request #55
Opened 2021-07-26 10:54 UTC by luhc228

Closed: #51 

### 外网
![image](https://user-images.githubusercontent.com/44047106/126977768-e4c40279-21b3-4840-9391-4dc0f6b28910.png)

### 内网
![image](https://user-images.githubusercontent.com/44047106/126977787-03dd8030-f92f-4375-bd64-e4970539e121.png)

2021-07-26 11:07 UTC, imsobear requested changes

2021-07-26 11:07 UTC, imsobear commented on main/data/data.json
> +      "registry": "https://registry.npmjs.org",
默认貌似是有 `/` 结尾的
![image](https://user-images.githubusercontent.com/2505411/126978876-b7f90965-0ed8-45ad-a8a6-bcb58c7403bd.png)

2021-07-26 11:07 UTC, imsobear commented on main/npm/registry.ts
> +  }
这个逻辑感觉写复杂了：

```
npmRegistries.forEach(item => {
  item.recommended = isAliInternal ? item.registry === ALI_NPM_REGISTRY : item.registry === TAOBAO_NPM_REGISTRY;
});
```

2021-07-26 11:07 UTC, imsobear commented on main/npm/registry.ts
> +  }
另外安装依赖的地方是不是要强制提示下？比如如果要安装 `@ali/xxx` 的包，但是 registry 不是 ali 源，这时候直接强制替换掉（只是这次安装替换）

2021-07-28 03:28 UTC, luhc228 commented on main/data/data.json
> +      "registry": "https://registry.npmjs.org",
修改过来了

2021-07-28 03:28 UTC, luhc228 commented on main/npm/registry.ts
> +  }
> 这个逻辑感觉写复杂了：
> 
> ```
> npmRegistries.forEach(item => {
>   item.recommended = isAliInternal ? item.registry === ALI_NPM_REGISTRY : item.registry === TAOBAO_NPM_REGISTRY;
> });
> ```

fixed

2021-08-03 03:16 UTC, fyangstudio approved these changes

2021-08-03 04:18 UTC, imsobear approved these changes

2021-08-03 05:21 UTC, merged